# ---------------- #
#   Main Configs   #
# ---------------- #
date_format: "ordinal"
title: foolchild
author: foolchild
paginate: 12
url: foolchild.cn


# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title
gems:
    - jekyll-sitemap
    - jekyll-paginate


# ---------------- #
#      Comments    #
# ---------------- #
duoshuo_short_name: lcj1992

# ---------------- #
#      Adsense     #
# ---------------- #
adsense: true
amazon: false
